<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	  <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <None Include="bin\Debug\net8.0-windows\Autogen\avcodec-61.dll" />
    <None Include="bin\Debug\net8.0-windows\Autogen\avdevice-61.dll" />
    <None Include="bin\Debug\net8.0-windows\Autogen\avfilter-10.dll" />
    <None Include="bin\Debug\net8.0-windows\Autogen\avformat-61.dll" />
    <None Include="bin\Debug\net8.0-windows\Autogen\avutil-59.dll" />
    <None Include="bin\Debug\net8.0-windows\Autogen\postproc-58.dll" />
    <None Include="bin\Debug\net8.0-windows\Autogen\swresample-5.dll" />
    <None Include="bin\Debug\net8.0-windows\Autogen\swscale-8.dll" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CppSharp" Version="1.1.5.3168" />
    <PackageReference Include="FFmpeg.AutoGen" Version="8.0.0" />
    <PackageReference Include="MahApps.Metro" Version="2.4.11" />
    <PackageReference Include="MahApps.Metro.IconPacks" Version="6.2.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Prism.Core" Version="9.0.537" />
    <PackageReference Include="Prism.Unity" Version="9.0.537" />
    <PackageReference Include="Prism.Wpf" Version="9.0.537" />
    <PackageReference Include="SharpDX.Mathematics" Version="4.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="8.0.10" />
  </ItemGroup>

 
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\RenderANDVideoReaderVIdeoDecoder\RenderANDVideoReaderVIdeoDecoder.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Reference Include="LibraryForSignalR">
	    <HintPath>..\..\..\DllForSignalR\JHent01\LibraryForSignalR\bin\Debug\LibraryForSignalR.dll</HintPath>
	  </Reference>
	</ItemGroup>
</Project>
